[
  { Hash: 'hn-cp-ca', Id: 402, Name: 'Cabañas' },
  { Hash: 'hn-cp-cn', Id: 403, Name: 'Concepción' },
  { Hash: 'hn-cp-cr', Id: 404, Name: 'Copán Ruinas' },
  { Hash: 'hn-cp-cq', Id: 405, Name: 'Corquín' },
  { Hash: 'hn-cp-cu', Id: 406, Name: 'Cucuyagua' },
  { Hash: 'hn-cp-do', Id: 407, Name: 'Dolores' },
  { Hash: 'hn-cp-dn', Id: 408, Name: 'Dulce Nombre' },
  { Hash: 'hn-cp-ep', Id: 409, Name: 'El Paraíso' },
  { Hash: 'hn-cp-fl', Id: 410, Name: 'Florida' },
  { Hash: 'hn-cp-lj', Id: 411, Name: 'La Jigua' },
  { Hash: 'hn-cp-lu', Id: 412, Name: 'La Unión' },
  { Hash: 'hn-cp-na', Id: 413, Name: 'Nueva Arcadia' },
  { Hash: 'hn-cp-sg', Id: 414, Name: 'San Agustín' },
  { Hash: 'hn-cp-sa', Id: 415, Name: 'San Antonio' },
  { Hash: 'hn-cp-sm', Id: 416, Name: 'San Jerónimo' },
  { Hash: 'hn-cp-sj', Id: 417, Name: 'San José' },
  { Hash: 'hn-cp-so', Id: 418, Name: 'San Juan de Opoa' },        
  { Hash: 'hn-cp-sn', Id: 419, Name: 'San Nicolás' },
  { Hash: 'hn-cp-sp', Id: 420, Name: 'San Pedro de Copán' },      
  { Hash: 'hn-cp-sr', Id: 421, Name: 'Santa Rita' },
  { Hash: 'hn-cp-sc', Id: 401, Name: 'Santa Rosa de Copán' },     
  { Hash: 'hn-cp-tc', Id: 422, Name: 'Trinidad de Copán' },       
  { Hash: 'hn-cp-ve', Id: 423, Name: 'Veracruz' }
]