[
    { Hash: 'hn-ep-al', Id: 702, Name: 'Alauca' },
    { Hash: 'hn-ep-da', Id: 703, Name: 'Danlí' },
    { Hash: 'hn-ep-ep', Id: 704, Name: 'El Paraíso' },
    { Hash: 'hn-ep-gu', Id: 705, Name: 'Güinope' },
    { Hash: 'hn-ep-ja', Id: 706, Name: 'Jacaleapa' },
    { Hash: 'hn-ep-li', Id: 707, Name: 'Liure' },
    { Hash: 'hn-ep-mo', Id: 708, Name: 'Morocelí' },
    { Hash: 'hn-ep-or', Id: 709, Name: 'Oropolí' },
    { Hash: 'hn-ep-po', Id: 710, Name: 'Potrerillos' },
    { Hash: 'hn-ep-sa', Id: 711, Name: 'San Antonio de Flores' },
    { Hash: 'hn-ep-sl', Id: 712, Name: 'San Lucas' },
    { Hash: 'hn-ep-sm', Id: 713, Name: 'San Matías' },
    { Hash: 'hn-ep-so', Id: 714, Name: 'Soledad' },
    { Hash: 'hn-ep-tp', Id: 715, Name: 'Teupasenti' },
    { Hash: 'hn-ep-tx', Id: 716, Name: 'Texiguat' },
    { Hash: 'hn-ep-tr', Id: 719, Name: 'Trojes' },
    { Hash: 'hn-ep-va', Id: 717, Name: 'Vado Ancho' },
    { Hash: 'hn-ep-ya', Id: 718, Name: 'Yauyupe' },
    { Hash: 'hn-ep-yu', Id: 701, Name: 'Yuscarán' }
]