[
    { Hash: 'hn-fm-al', Id: 802, Name: 'Alubarén' },
    { Hash: 'hn-fm-ce', Id: 803, Name: 'Cedros' },
    { Hash: 'hn-fm-cu', Id: 804, Name: 'Curarén' },
    { Hash: 'hn-fm-dc', Id: 801, Name: 'Distrito Central' },
    { Hash: 'hn-fm-ep', Id: 805, Name: 'El Porvenir' },
    { Hash: 'hn-fm-gu', Id: 806, Name: 'Guaimaca' },
    { Hash: 'hn-fm-ll', Id: 807, Name: 'La Libertad' },
    { Hash: 'hn-fm-lv', Id: 808, Name: 'La Venta' },
    { Hash: 'hn-fm-le', Id: 809, Name: 'Lepaterique' },
    { Hash: 'hn-fm-mt', Id: 810, Name: 'Maraita' },
    { Hash: 'hn-fm-ml', Id: 811, Name: 'Marale' },
    { Hash: 'hn-fm-na', Id: 812, Name: 'Nueva Armenia' },
    { Hash: 'hn-fm-oj', Id: 813, Name: 'Ojojona' },
    { Hash: 'hn-fm-or', Id: 814, Name: 'Orica' },
    { Hash: 'hn-fm-re', Id: 815, Name: 'Reitoca' },
    { Hash: 'hn-fm-sg', Id: 816, Name: 'Sabanagrande' },
    { Hash: 'hn-fm-so', Id: 817, Name: 'San Antonio de Oriente' },
    { Hash: 'hn-fm-sb', Id: 818, Name: 'San Buenaventura' },
    { Hash: 'hn-fm-si', Id: 819, Name: 'San Ignacio' },
    { Hash: 'hn-fm-sj', Id: 820, Name: 'San Juan de Flores' },
    { Hash: 'hn-fm-sm', Id: 821, Name: 'San Miguelito' },
    { Hash: 'hn-fm-sa', Id: 822, Name: 'Santa Ana' },
    { Hash: 'hn-fm-sl', Id: 823, Name: 'Santa Lucía' },
    { Hash: 'hn-fm-tl', Id: 824, Name: 'Talanga' },
    { Hash: 'hn-fm-tt', Id: 825, Name: 'Tatumbla' },
    { Hash: 'hn-fm-va', Id: 826, Name: 'Valle de Ángeles' },
    { Hash: 'hn-fm-vc', Id: 828, Name: 'Vallecillo' },
    { Hash: 'hn-fm-vs', Id: 827, Name: 'Villa de San Francisco' }
]