[
    { Hash: 'hn-lp-ag', Id: 1202, Name: 'Aguanqueterique' },
    { Hash: 'hn-lp-cb', Id: 1203, Name: 'Cabañas' },
    { Hash: 'hn-lp-cn', Id: 1204, Name: 'Cane' },
    { Hash: 'hn-lp-ch', Id: 1205, Name: 'Chinacla' },
    { Hash: 'hn-lp-gu', Id: 1206, Name: 'Guajiquiro' },
    { Hash: 'hn-lp-lp', Id: 1201, Name: 'La Paz' },
    { Hash: 'hn-lp-la', Id: 1207, Name: 'Lauterique' },
    { Hash: 'hn-lp-ma', Id: 1208, Name: 'Marcala' },
    { Hash: 'hn-lp-mo', Id: 1209, Name: 'Mercedes de Oriente' },
    { Hash: 'hn-lp-op', Id: 1210, Name: 'Opatoro' },
    { Hash: 'hn-lp-sn', Id: 1211, Name: 'San Antonio del Norte' },
    { Hash: 'hn-lp-sj', Id: 1212, Name: 'San José' },
    { Hash: 'hn-lp-su', Id: 1213, Name: 'San Juan' },
    { Hash: 'hn-lp-st', Id: 1214, Name: 'San Pedro de Tutule' },
    { Hash: 'hn-lp-sa', Id: 1215, Name: 'Santa Ana' },
    { Hash: 'hn-lp-se', Id: 1216, Name: 'Santa Elena' },
    { Hash: 'hn-lp-sm', Id: 1217, Name: 'Santa María' },
    { Hash: 'hn-lp-sp', Id: 1218, Name: 'Santiago de Puringla' },
    { Hash: 'hn-lp-ya', Id: 1219, Name: 'Yarula' }
]