[
    { Hash: 'hn-le-be', Id: 1302, Name: 'Belén' },
    { Hash: 'hn-le-ca', Id: 1303, Name: 'Candelaria' },
    { Hash: 'hn-le-co', Id: 1304, Name: 'Cololaca' },
    { Hash: 'hn-le-er', Id: 1305, Name: 'Erandique' },
    { Hash: 'hn-le-gr', Id: 1301, Name: 'Gracias' },
    { Hash: 'hn-le-gc', Id: 1306, Name: 'Gualcince' },
    { Hash: 'hn-le-gt', Id: 1307, Name: 'Guarita' },
    { Hash: 'hn-le-lc', Id: 1308, Name: 'La Campa' },
    { Hash: 'hn-le-li', Id: 1309, Name: 'La Iguala' },
    { Hash: 'hn-le-lu', Id: 1311, Name: 'La Unión' },
    { Hash: 'hn-le-lv', Id: 1312, Name: 'La Virtud' },
    { Hash: 'hn-le-lf', Id: 1310, Name: 'Las Flores' },
    { Hash: 'hn-le-le', Id: 1313, Name: 'Lepaera' },
    { Hash: 'hn-le-ma', Id: 1314, Name: 'Mapulaca' },
    { Hash: 'hn-le-pi', Id: 1315, Name: 'Piraera' },
    { Hash: 'hn-le-sa', Id: 1316, Name: 'San Andrés' },
    { Hash: 'hn-le-sf', Id: 1317, Name: 'San Francisco' },
    { Hash: 'hn-le-sj', Id: 1318, Name: 'San Juan Guarita' },      
    { Hash: 'hn-le-sh', Id: 1319, Name: 'San Manuel Colohete' },   
    { Hash: 'hn-le-sm', Id: 1328, Name: 'San Marcos de Caiquín' }, 
    { Hash: 'hn-le-sr', Id: 1320, Name: 'San Rafael' },
    { Hash: 'hn-le-ss', Id: 1321, Name: 'San Sebastián' },
    { Hash: 'hn-le-sc', Id: 1322, Name: 'Santa Cruz' },
    { Hash: 'hn-le-tg', Id: 1323, Name: 'Talgua' },
    { Hash: 'hn-le-tb', Id: 1324, Name: 'Tambla' },
    { Hash: 'hn-le-to', Id: 1325, Name: 'Tomalá' },
    { Hash: 'hn-le-va', Id: 1326, Name: 'Valladolid' },
    { Hash: 'hn-le-vi', Id: 1327, Name: 'Virginia' }
  ]