[
    { Hash: 'hn-ol-cp', Id: 1502, Name: 'Campamento' },
    { Hash: 'hn-ol-ct', Id: 1503, Name: 'Catacamas' },
    { Hash: 'hn-ol-co', Id: 1504, Name: 'Concordia' },
    { Hash: 'hn-ol-dn', Id: 1505, Name: 'Dulce Nombre de Culmí' },
    { Hash: 'hn-ol-er', Id: 1506, Name: 'El Rosario' },
    { Hash: 'hn-ol-en', Id: 1507, Name: 'Esquipulas del Norte' },
    { Hash: 'hn-ol-gl', Id: 1508, Name: 'Gualaco' },
    { Hash: 'hn-ol-gr', Id: 1509, Name: 'Guarizama' },
    { Hash: 'hn-ol-gt', Id: 1510, Name: 'Guata' },
    { Hash: 'hn-ol-gy', Id: 1511, Name: 'Guayape' },
    { Hash: 'hn-ol-ja', Id: 1512, Name: 'Jano' },
    { Hash: 'hn-ol-ju', Id: 1501, Name: 'Juticalpa' },
    { Hash: 'hn-ol-lu', Id: 1513, Name: 'La Unión' },
    { Hash: 'hn-ol-mg', Id: 1514, Name: 'Mangulile' },
    { Hash: 'hn-ol-mt', Id: 1515, Name: 'Manto' },
    { Hash: 'hn-ol-pa', Id: 1523, Name: 'Patuca' },
    { Hash: 'hn-ol-sa', Id: 1516, Name: 'Salamá' },
    { Hash: 'hn-ol-se', Id: 1517, Name: 'San Esteban' },
    { Hash: 'hn-ol-sb', Id: 1518, Name: 'San Francisco de Becerra' },
    { Hash: 'hn-ol-sp', Id: 1519, Name: 'San Francisco de La Paz' },
    { Hash: 'hn-ol-sm', Id: 1520, Name: 'Santa María del Real' },
    { Hash: 'hn-ol-si', Id: 1521, Name: 'Silca' },
    { Hash: 'hn-ol-yo', Id: 1522, Name: 'Yocón' }
  ]