[
    { Hash: 'hn-sb-ar', Id: 1602, Name: 'Arada' },
    { Hash: 'hn-sb-at', Id: 1603, Name: 'Atima' },
    { Hash: 'hn-sb-az', Id: 1604, Name: 'Azacualpa' },
    { Hash: 'hn-sb-ce', Id: 1605, Name: 'Ceguaca' },
    { Hash: 'hn-sb-ch', Id: 1606, Name: 'Chinda' },
    { Hash: 'hn-sb-cn', Id: 1607, Name: 'Concepción del Norte' },
    { Hash: 'hn-sb-cs', Id: 1608, Name: 'Concepción del Sur' },  
    { Hash: 'hn-sb-en', Id: 1610, Name: 'El Níspero' },
    { Hash: 'hn-sb-gu', Id: 1611, Name: 'Gualala' },
    { Hash: 'hn-sb-il', Id: 1612, Name: 'Ilama' },
    { Hash: 'hn-sb-lv', Id: 1627, Name: 'Las Vegas' },
    { Hash: 'hn-sb-ma', Id: 1613, Name: 'Macuelizo' },
    { Hash: 'hn-sb-na', Id: 1614, Name: 'Naranjito' },
    { Hash: 'hn-sb-nf', Id: 1628, Name: 'Nueva Frontera' },
    { Hash: 'hn-sb-nc', Id: 1615, Name: 'Nuevo Celilac' },
    { Hash: 'hn-sb-pe', Id: 1616, Name: 'Petoa' },
    { Hash: 'hn-sb-pr', Id: 1617, Name: 'Protección' },
    { Hash: 'hn-sb-qu', Id: 1618, Name: 'Quimistán' },
    { Hash: 'hn-sb-sf', Id: 1619, Name: 'San Francisco de Ojuera' },
    { Hash: 'hn-sb-sj', Id: 1609, Name: 'San José de Colinas' },
    { Hash: 'hn-sb-sl', Id: 1620, Name: 'San Luis' },
    { Hash: 'hn-sb-sm', Id: 1621, Name: 'San Marcos' },
    { Hash: 'hn-sb-sn', Id: 1622, Name: 'San Nicolás' },
    { Hash: 'hn-sb-sp', Id: 1623, Name: 'San Pedro Zacapa' },
    { Hash: 'hn-sb-sv', Id: 1625, Name: 'San Vicente Centenario' },
    { Hash: 'hn-sb-sb', Id: 1601, Name: 'Santa Bárbara' },
    { Hash: 'hn-sb-sr', Id: 1624, Name: 'Santa Rita' },
    { Hash: 'hn-sb-tr', Id: 1626, Name: 'Trinidad' }
  ]